repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint must pass
        language: system
        entry: golangci-lint run --timeout 5m0s --fix
        pass_filenames: false

      - id: go-mod-tidy
        name: run go mod tidy
        language: system
        entry: go mod tidy
        pass_filenames: false
